namespace RPGFramework.Field
{
    internal enum FieldScriptOpCode : ushort
    {
        // Script Flow and Control
        Return,                                  //
        RunAnotherEntityScriptUnlessBusy,        // byte targetEntityId, byte targetScriptId
        RunAnotherEntityScriptWaitUntilStarted,  // byte targetEntityId, byte targetScriptId
        RunAnotherEntityScriptWaitUntilFinished, // byte targetEntityId, byte targetScriptId
        RunPartyMemberScriptUnlessBusy,
        RunPartyMemberScriptWaitUntilStarted,
        RunPartyMemberScriptWaitUntilFinished,
        ReturnToAnotherScript, // byte targetScriptId
        Goto,                  // int offset
        CompareTwoByteValues,
        CompareTwoIntValues,
        Yield,       //
        WaitSeconds, // float seconds
        IfKeyIsDown,
        IfKeyWasJustPressed,
        IfKeyWasJustReleased,
        DoNothing, //
        IfCharacterIsInParty,
        IfCharacterIsAvailable,

        // System and Module Control
        SpecialOp,
        RunMinigame,
        SetBattleModeOptions,
        LoadResultOfLastBattle,
        SetBattleEncounterTable,
        JumpToAnotherMap,
        GetLastFieldMap,
        StartBattle,
        RandomEncounters,
        SetBattleModeOptionsAgain,
        GatewayTriggerActivation,
        GameOver,

        // Assignment and Mathematics
        Addition8BitClamped,
        Addition16BitClamped,
        Subtraction8BitClamped,
        Subtraction16BitClamped,
        Increment8BitClamped,
        Increment16BitClamped,
        Decrement8BitClamped,
        Decrement16BitClamped,
        RandomNumberSeed,
        AssignValue8Bit,
        AssignValue16Bit,
        SetBit,
        UnsetBit,
        Unused,
        Addition8Bit,
        Addition16Bit,
        Subtraction8Bit,
        Subtraction16Bit,
        Multiplication8Bit,
        Multiplication16Bit,
        Division8Bit,
        Division16Bit,
        Remainder8Bit,
        Remainder16Bit,
        BitwiseAnd8Bit,
        BitwiseAnd16Bit,
        BitwiseOr8Bit,
        BitwiseOr16Bit,
        BitwiseXor8Bit,
        BitwiseXor16Bit,
        Increment8Bit,
        Increment16Bit,
        Decrement8Bit,
        Decrement16Bit,
        GetRandomNumber,
        GetLowByte,
        GetHighByte,
        GetTwoBytes,
        Sine,
        Cosine,

        // Windowing and Menu
        RunTutorial,
        CloseWindow,
        ResizeWindow,
        CreateSpecialWindow,
        SetNumberInWindow,
        SetTimeInWindow,
        ShowWindowWithText,
        SetWindowTextValue,
        SetWindowTextValue16Bit,
        SetMapNameInMenu,
        AskPlayerToMakeAChoice,
        MenuOperations,
        MainMenuAccessibility,
        CreateWindow,
        SetWindowPosition,
        SetWindowModes,
        ResetWindow,
        CloseWindowAgain,
        SetNumberOfRowsInWindow,

        // Party and Inventory
        ChangePartyMembers,
        StorePartyMembers,
        IncreaseGil,
        DecreaseGil,
        GetGilAmount,
        Unused1,
        Unused2,
        RestoreHPMP,
        RestoreHPMPAgain,
        IncreaseMP,
        DecreaseMP,
        IncreaseHP,
        DecreaseHP,
        AddItemToInventory,
        RemoveItemFromInventory,
        GetItemCountFromInventory,
        AddMateriaToInventory,
        RemoveMateriaFromInventory,
        MateriaOpC,
        GetPartyMembersIdentity,
        AddCharacterToParty,
        RemoveCharacterFromParty,
        SetAllPartyCharacters,
        IfCharacterIsInPartyAgain,
        IfCharacterIsAvailableAgain,
        SetCharacterAvailability,
        LockPartyMember,
        UnlockPartyMember,

        // Field Models and Animation
        JoinPartyToLeader,
        SplitPartyFromLeader,
        CharacterGraphicsOp,
        WaitForGraphicsOp,
        MoveToPartyMember,
        SlipAgainstWalls,
        PlayerMovability,
        FaceCharacter,
        TurnToPartyMember,
        CollisionDetection,
        GetPartyMemberDirection,
        GetPartyMemberPosition,
        Interactibility,
        InitAsFieldModel,
        InitAsCharacter,
        PlayAnimationLooping,
        PlayAnimationOnceAndWait,
        Visibility,
        SetEntityLocationXYZI,
        SetEntityLocationXYI,
        SetEntityLocationXYZ,
        MoveEntityToXYWalkAnimation,
        MoveEntityToXYNoAnimation,
        MoveEntityToAnotherEntity,
        TurnEntityToAnotherEntity,
        WaitForAnimation,
        MoveFieldObject,
        PlayAnimationAsync,
        PlayAnimationOnceAsync,
        PlayPartialAnimation,
        PlayPartialAnimationAgain,
        SetMovementSpeed,
        SetFacingDirection,
        RotateModel,
        SetDirectionToFaceEntity,
        GetEntityDirection,
        GetEntityLocationXY,
        GetEntityDirectionI,
        PlayAnimationStopOnLastFrameWait,
        PlayAnimationToDo,
        PlayAnimationToDoAgain,
        SetAnimationSpeed,
        SetEntityAsControllableCharacter,
        MakeEntityJump,
        GetEntityPositionXYZI,
        ClimbLadder,
        TransposeObjectVisualizationOnly,
        WaitForTranspose,
        SetInteractibilityRadius,
        SetCollisionRadius,
        Collidability,
        LineTriggerInitialization,
        LineTriggerActivation,
        SetLine,
        SetInteractibilityRadiusAgain,
        SetCollisionRadiusAgain,
        FixFacingForward,
        SetAnimationID,
        StopAnimation,
        WaitForTurn,

        // Background and Palette
        SetBackgroundDepth,
        ScrollBackground,
        MultiplyPaletteColors,
        BackgroundOn,
        BackgroundOff,
        BackgroundRollForward,
        BackgroundRollBackward,
        BackgroundClear,
        StorePalette,
        LoadPalette,
        CopyPalette,
        CopyPalettePartial,
        AddToPaletteColorValues,
        MultiplyPaletteColorValues,
        StorePaletteOffset,
        LoadPaletteOffset,
        CopyPaletteAgain,
        ReturnPalette,
        AddPalette,

        // Camera, Audio and Video
        FadeScreen,
        ShakeScreen,
        ScrollScreen,
        ScrollScreenAgain,
        ScrollScreenToEntity,
        ScrollScreenToPosition,
        ScrollScreenToLeader,
        StartTheScreenToPositionEaseInOut,
        WaitForScrolling,
        StartTheScreenToPositionLinear,
        FadeScreenWait,
        WaitForFade,
        ScrollToPartyMember,
        MusicOperation,
        PlayMusic, // int id
        PlaySound, // int id
        MusicOperationAgain,
        MusicVT,
        MusicVM,
        MusicLockMode,
        SetBattleMusic,
        Unknown,
        MusicOpF,
        MusicOpC,
        CheckIfMusicIsPlaying,

        // Uncategorized
        Something,
        SomethingAgain,
        SetX,
        GetX,
        SearchForValueInData,
        SetJumpFieldID,
        SetJumpFieldIDAgain,
    }
}