using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using RPGFramework.Core.Memory;
using RPGFramework.Hashing;
using UnityEditor;
using UnityEngine;

namespace RPGFramework.Field.Editor
{
    [Serializable]
    internal class FieldDatabase
    {
        private readonly string m_AssetBundlesPath = Path.Combine(Application.streamingAssetsPath, "Field");

        [SerializeField]
        private List<FieldDatabaseAssetAuthoring> m_Fields = new List<FieldDatabaseAssetAuthoring>();

        public List<FieldDatabaseAssetAuthoring> Fields => m_Fields;

        public void BuildScriptFile(string path, string filename, string namespaceForScript)
        {
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, filename);

            if (File.Exists(filePath))
            {
                File.Delete(filePath);
            }

            int           count          = m_Fields.Count;
            StringBuilder sb             = new StringBuilder();
            string        scriptFileName = filename.Split('.')[0];

            sb.AppendLine("// THIS FILE IS AUTOGENERATED, DO NOT MODIFY");
            sb.AppendLine($"// Last generated at {DateTime.UtcNow}\n");

            sb.AppendLine("using RPGFramework.Field;");
            sb.AppendLine("using RPGFramework.Hashing;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceForScript}");
            sb.AppendLine("{");

            sb.AppendLine($"\tinternal class {scriptFileName.Replace(" ", "")} : IFieldDatabase");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tprivate readonly Dictionary<ulong, FieldDatabaseAsset> m_FieldsByNameHash;");
            sb.AppendLine();
            sb.AppendLine($"\t\tinternal {scriptFileName.Replace(" ", "")}()");
            sb.AppendLine("\t\t{");

            sb.AppendLine("\t\t\tstring assetBundlesPath = Path.Combine(Application.streamingAssetsPath, \"Field\");");
            sb.AppendLine($"\t\t\tm_FieldsByNameHash = new Dictionary<ulong, FieldDatabaseAsset>({count})");
            sb.AppendLine("\t\t\t{");
            for (int i = 0; i < count; i++)
            {
                string fieldName = m_Fields[i].Prefab.name;

                sb.AppendLine($"\t\t\t\t[Fnv1a64.Hash(\"{fieldName}\")] = new FieldDatabaseAsset(\"{fieldName}\", Path.Combine(assetBundlesPath, \"{fieldName.ToLower()}\"),");
                sb.AppendLine("\t\t\t\t\tnew string[]");
                sb.AppendLine("\t\t\t\t\t{");
                for (int j = 0; j < m_Fields[i].LocalisationSheets.Length; j++)
                {
                    sb.AppendLine($"\t\t\t\t\t\t\"{m_Fields[i].LocalisationSheets[j].SheetName}\",");
                }

                sb.AppendLine("\t\t\t\t\t}");
                sb.AppendLine($"\t\t\t\t),");
            }

            sb.AppendLine("\t\t\t};");

            sb.AppendLine("\t\t}");

            sb.AppendLine();

            sb.AppendLine("\t\tFieldDatabaseAsset IFieldDatabase.Get(ulong fieldNameHash)");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\treturn m_FieldsByNameHash[fieldNameHash];");
            sb.AppendLine("\t\t}");

            sb.AppendLine("\t}");

            sb.AppendLine("}");

            string file = sb.ToString();

            File.WriteAllText(filePath, file);

            AssetDatabase.Refresh();
        }

        /// <summary>
        /// Check every field's entities before their data is exported.<br /><br />
        /// Script 0 is an entity's init script by convention, and the field module runs it at load. An
        /// entity whose scripts were authored in another order would have its enter or interaction
        /// script executed at field load, firing gameplay logic nobody triggered.<br /><br />
        /// This is checked here rather than at runtime deliberately. A per-load check re-proves the same
        /// thing on every field load forever, and reports the problem while playing; checking as the
        /// runtime data is built reports it once, while authoring, to the person who can fix it.
        /// </summary>
        /// <returns>A readable problem per offending entity. Empty means every field is well-formed.</returns>
        public List<string> ValidateFields()
        {
            List<string> problems = new List<string>();

            for (int i = 0; i < m_Fields.Count; i++)
            {
                GameObject prefab = m_Fields[i].Prefab;

                if (prefab == null)
                {
                    problems.Add($"Field [{i}] has no prefab assigned");
                    continue;
                }

                FieldEntity[] entities = prefab.GetComponentsInChildren<FieldEntity>(true);

                HashSet<int>            entityIds        = new HashSet<int>();
                Dictionary<int, string> scriptIds        = new Dictionary<int, string>();
                DialogueChannelUse      dialogueChannels = new DialogueChannelUse();

                foreach (FieldEntity entity in entities)
                {
                    ValidateEntity(prefab, entity, entityIds, scriptIds, dialogueChannels, problems);
                }

                dialogueChannels.Validate(prefab.name, problems);
            }

            ValidateVariableMaps(problems);

            return problems;
        }

        /// <summary>
        /// The variable map is part of what a field export depends on: a new game begins at the defaults of
        /// <see cref="FieldVariables.CURRENT_FIELD" /> and <see cref="FieldVariables.CURRENT_SPAWN" />, so they have to
        /// name a field in this database and a spawn point it has, and the map has to declare everything the
        /// framework reads from it.
        /// </summary>
        private void ValidateVariableMaps(List<string> problems)
        {
            string[] guids = AssetDatabase.FindAssets("t:" + nameof(VariableMapAsset));

            if (guids.Length == 0)
            {
                problems.Add($"No {nameof(VariableMapAsset)} in the project. A new game reads where to begin from it — create one with RPG Framework / Core / Variable Map");
                return;
            }

            foreach (string guid in guids)
            {
                VariableMapAsset map = AssetDatabase.LoadAssetAtPath<VariableMapAsset>(AssetDatabase.GUIDToAssetPath(guid));

                foreach (string problem in map.Validate())
                {
                    problems.Add($"Variable map '{map.name}': {problem}");
                }

                if (!map.TryGetVariable(FieldVariables.CURRENT_FIELD, out VariableDefinition field) ||
                    !map.TryGetVariable(FieldVariables.CURRENT_SPAWN, out VariableDefinition spawn))
                {
                    continue;
                }

                GameObject start = FindFieldPrefab(field.DefaultValue);

                if (start == null)
                {
                    problems.Add($"Variable map '{map.name}': '{FieldVariables.CURRENT_FIELD}' does not default to a field in this database, so a new game has nowhere to begin. Choose one in the Variable Map inspector");
                    continue;
                }

                int spawnId = (int)VariableDefaults.ToInteger(spawn.DefaultValue, VariableWidth.Int);

                if (Array.Find(start.GetComponentsInChildren<SpawnPoint>(true), spawnPoint => spawnPoint.Id == spawnId) == null)
                {
                    problems.Add($"Variable map '{map.name}': '{FieldVariables.CURRENT_SPAWN}' defaults to spawn point [{spawnId}], which {start.name} does not have");
                }
            }
        }

        private GameObject FindFieldPrefab(ulong fieldNameHash)
        {
            foreach (FieldDatabaseAssetAuthoring field in m_Fields)
            {
                if (field.Prefab != null && Fnv1a64.Hash(field.Prefab.name) == fieldNameHash)
                {
                    return field.Prefab;
                }
            }

            return null;
        }

        /// <summary>
        /// A field entity's rigidbody has to be kinematic.<br /><br />
        /// Entities are never moved by the physics simulation: the movement drivers sweep a kinematic body
        /// along its path and slide it along what it meets. A dynamic body instead takes momentum from every
        /// collision — walk into one and both float away, with nothing to slow them — so it is refused here,
        /// where it can be fixed, rather than discovered in play.
        /// </summary>
        private static void ValidateEntityPhysics(FieldEntity entity, string entityName, List<string> problems)
        {
            if (entity.TryGetComponent(out Rigidbody body) && !body.isKinematic)
            {
                problems.Add($"{entityName} has a dynamic {nameof(Rigidbody)}. Field entities must be kinematic, so collisions cannot push them — tick Is Kinematic");
            }

            if (entity.TryGetComponent(out Rigidbody2D body2D) && body2D.bodyType != RigidbodyType2D.Kinematic)
            {
                problems.Add($"{entityName} has a {body2D.bodyType} {nameof(Rigidbody2D)}. Field entities must be kinematic, so collisions cannot push them — set Body Type to Kinematic");
            }
        }

        /// <summary>
        /// Everything about one entity that has to be true before its field is exported, and that cannot
        /// change afterwards. The VM addresses entities and scripts by index at runtime with no way to
        /// report which authored thing was wrong, so it is all decided here instead.
        /// </summary>
        private void ValidateEntity(GameObject prefab, FieldEntity entity, HashSet<int> entityIds, Dictionary<int, string> scriptIds, DialogueChannelUse dialogueChannels, List<string> problems)
        {
            FieldScriptDefinition scriptDefinition = entity.ScriptDefinition;

            if (scriptDefinition == null)
            {
                problems.Add($"{prefab.name} / '{entity.name}' has no {nameof(FieldScriptDefinition)}");
                return;
            }

            string entityName = $"{prefab.name} / '{scriptDefinition.EntityName}'";

            // Scripts address each other by entity id, so two entities sharing one makes the target
            // ambiguous — and the VM's entity dictionary would throw on the duplicate key at load.
            if (!entityIds.Add(scriptDefinition.EntityId))
            {
                problems.Add($"{entityName} reuses entity id [{scriptDefinition.EntityId}], which another entity in this field already has");
            }

            ValidateEntityPhysics(entity, entityName, problems);

            if (scriptDefinition.Scripts == null || scriptDefinition.Scripts.Count == 0)
            {
                problems.Add($"{entityName} declares no scripts, so it has no init script");
                return;
            }

            FieldScriptType firstScriptType = scriptDefinition.Scripts[0].ScriptType;

            if (firstScriptType != FieldScriptType.Init)
            {
                problems.Add($"{entityName} has [{firstScriptType}] as its first script, but script 0 is run at field load as the init script. Reorder so the {nameof(FieldScriptType.Init)} script is first");
            }

            int initScriptCount    = 0;
            int defaultScriptCount = 0;

            for (int i = 0; i < scriptDefinition.Scripts.Count; i++)
            {
                ScriptEntry scriptEntry = scriptDefinition.Scripts[i];

                if (scriptEntry.ScriptType == FieldScriptType.Init)
                {
                    initScriptCount++;
                }

                if (scriptEntry.ScriptType == FieldScriptType.Default)
                {
                    defaultScriptCount++;
                }

                if (scriptEntry.CompiledScript == null)
                {
                    problems.Add($"{entityName} script [{i}] ({scriptEntry.ScriptType}) has no compiled script assigned");
                    continue;
                }

                if (scriptEntry.CompiledScript.Bytecode == null || scriptEntry.CompiledScript.Bytecode.Length == 0)
                {
                    problems.Add($"{entityName} script [{i}] ({scriptEntry.ScriptType}) compiled to no bytecode — recompile it from its {nameof(FieldScriptSource)}");
                }

                // The authored script id is the runtime address: it is what the VM registers scripts
                // under and what triggers and script-request opcodes name. Two scripts sharing one in the
                // same field means the second silently replaces the first.
                int scriptId = scriptEntry.CompiledScript.ScriptId;

                string scriptDescription = $"{entityName} script [{i}] ({scriptEntry.ScriptType})";

                if (scriptIds.TryGetValue(scriptId, out string owner))
                {
                    problems.Add($"{scriptDescription} uses script id [{scriptId}], which {owner} already uses");
                }
                else
                {
                    scriptIds.Add(scriptId, scriptDescription);
                }

                if (scriptId < 0 || scriptId > ushort.MaxValue)
                {
                    problems.Add($"{scriptDescription} has script id [{scriptId}], outside the 0..{ushort.MaxValue} a script-request opcode can address");
                }

                if (!FieldCompiledScriptAssets.TryFindSource(scriptEntry.CompiledScript, out FieldScriptSource source))
                {
                    problems.Add($"{scriptDescription} has no {nameof(FieldScriptSource)} beside it, so it cannot be recompiled or checked. A compiled script is written next to the source it came from");
                    continue;
                }

                string[] lines = source.ScriptText.Split('\n');

                ValidateInitScript(scriptEntry, scriptDescription, lines, problems);
                ValidateTriggerSwitches(entity, scriptDescription, lines, problems);
                ValidateMapJumps(scriptDescription, lines, problems);
                ValidateGatewayScript(scriptEntry, scriptDescription, lines, problems);
                dialogueChannels.Read(lines, scriptDescription);
            }

            if (initScriptCount > 1)
            {
                problems.Add($"{entityName} has {initScriptCount} {nameof(FieldScriptType.Init)} scripts, but only script 0 is run at load");
            }

            if (defaultScriptCount > 1)
            {
                problems.Add($"{entityName} has {defaultScriptCount} {nameof(FieldScriptType.Default)} scripts, but only one is started after initialisation");
            }

            ValidateGateway(prefab, entity, entityName, problems);
        }

        /// <summary>
        /// An init script that stops.<br /><br />
        /// Init runs straight through before the field is shown, so an opcode that blocks or ends the frame
        /// stops it there and everything after it never runs. The opcodes that do that declare
        /// <see cref="FieldOpCodeAttribute.StopsInit" />, so this reads the table rather than a list kept here.
        /// </summary>
        private static void ValidateInitScript(ScriptEntry scriptEntry, string scriptDescription, string[] lines, List<string> problems)
        {
            if (scriptEntry.ScriptType != FieldScriptType.Init)
            {
                return;
            }

            foreach (string line in lines)
            {
                string name = line.Trim().Split(' ')[0];

                if (FieldOpCodeCatalogue.TryGet(name, out FieldOpCodeInfo opCode) && opCode.StopsInit)
                {
                    problems.Add($"{scriptDescription} uses {name}, which waits or gives up the frame. Init runs straight through before the field is shown, so nothing after it would run — move it, and whatever follows it, into a {nameof(FieldScriptType.Default)} script");
                }
            }
        }

        /// <summary>
        /// A script switching a trigger its entity does not have. The field module reaches for the trigger
        /// without looking, so this is the only place the mistake can be caught.
        /// </summary>
        private static void ValidateTriggerSwitches(FieldEntity entity, string scriptDescription, string[] lines, List<string> problems)
        {
            bool hasCollisionTrigger   = entity.GetComponentInChildren<FieldCollisionTrigger>(true)   != null;
            bool hasInteractionTrigger = entity.GetComponentInChildren<FieldInteractionTrigger>(true) != null;

            foreach (string line in lines)
            {
                string name = line.Trim().Split(' ')[0];

                if (!FieldOpCodeCatalogue.TryGet(name, out FieldOpCodeInfo opCode))
                {
                    continue;
                }

                if (opCode.OpCode == FieldScriptOpCode.CollisionTriggerActivation && !hasCollisionTrigger)
                {
                    problems.Add($"{scriptDescription} uses {name}, but its entity has no {nameof(FieldCollisionTrigger)} to switch");
                }

                if ((opCode.OpCode == FieldScriptOpCode.InteractionTriggerActivation || opCode.OpCode == FieldScriptOpCode.SetInteractionRange) && !hasInteractionTrigger)
                {
                    problems.Add($"{scriptDescription} uses {name}, but its entity has no {nameof(FieldInteractionTrigger)} to change");
                }
            }
        }

        /// <summary>
        /// A way out of the field that is not a <see cref="FieldScriptType.Gateway" /> script, or a gateway that is
        /// not a way out.<br /><br />
        /// <c>GATEWAY_TRIGGER_ACTIVATION</c> switches scripts by their type, so the type is a promise about what the
        /// script does, and it is kept here. A gateway that never jumps is silenced by that switch for no reason; a
        /// jump on entering that is typed as something else is a way out the switch cannot stop, which is the whole
        /// point of the switch. Other script types are left alone: a cutscene ending in a map jump is ordinary, and
        /// only entering the trigger is what the switch is about.
        /// </summary>
        private static void ValidateGatewayScript(ScriptEntry scriptEntry, string scriptDescription, string[] lines, List<string> problems)
        {
            bool isGateway = scriptEntry.ScriptType == FieldScriptType.Gateway;
            bool isOnEnter = scriptEntry.ScriptType == FieldScriptType.OnEnter;

            if (!isGateway && !isOnEnter)
            {
                return;
            }

            bool jumps = HasMapJump(lines);

            if (isGateway == jumps)
            {
                return;
            }

            FieldOpCodeCatalogue.TryGet(FieldScriptOpCode.JumpToAnotherMap, out FieldOpCodeInfo jump);

            if (isGateway)
            {
                problems.Add($"{scriptDescription} is a {nameof(FieldScriptType.Gateway)} script with no {jump.ScriptName} in it, so it is not a way out of the field. {nameof(FieldScriptType.Gateway)} is what GATEWAY_TRIGGER_ACTIVATION switches — if this script does something else on entering, make it an {nameof(FieldScriptType.OnEnter)} script");
                return;
            }

            problems.Add($"{scriptDescription} is an {nameof(FieldScriptType.OnEnter)} script containing {jump.ScriptName}, so it is a way out of the field that GATEWAY_TRIGGER_ACTIVATION cannot stop. Make it a {nameof(FieldScriptType.Gateway)} script");
        }

        private static bool HasMapJump(string[] lines)
        {
            foreach (string line in lines)
            {
                if (FieldOpCodeCatalogue.TryGet(line.Trim().Split(' ')[0], out FieldOpCodeInfo opCode) && opCode.OpCode == FieldScriptOpCode.JumpToAnotherMap)
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// A map jump to a spawn point the field it names does not have. The name itself is checked when the
        /// script compiles; the spawn id is not, and at run time the player arrives wherever their init script
        /// left them instead. A spawn id read from a variable is only known then, so it is left alone.
        /// </summary>
        private void ValidateMapJumps(string scriptDescription, string[] lines, List<string> problems)
        {
            foreach (string line in lines)
            {
                string[] parts = line.Trim().Split(' ');

                if (!FieldOpCodeCatalogue.TryGet(parts[0], out FieldOpCodeInfo opCode) || opCode.OpCode != FieldScriptOpCode.JumpToAnotherMap)
                {
                    continue;
                }

                // A jump written with the wrong arguments, or naming a field nothing answers to, is the
                // compiler's to report, and it will not have produced the bytecode this entity holds.
                if (parts.Length < 3 || parts[2].StartsWith("$") || !int.TryParse(parts[2], NumberStyles.Integer, CultureInfo.InvariantCulture, out int spawnId))
                {
                    continue;
                }

                GameObject destination = FindFieldPrefab(parts[1]);

                if (destination == null)
                {
                    continue;
                }

                if (Array.Find(destination.GetComponentsInChildren<SpawnPoint>(true), spawnPoint => spawnPoint.Id == spawnId) == null)
                {
                    problems.Add($"{scriptDescription} jumps to spawn point [{spawnId}] in {parts[1]}, which has no {nameof(SpawnPoint)} with that id");
                }
            }
        }

        private GameObject FindFieldPrefab(string fieldName)
        {
            foreach (FieldDatabaseAssetAuthoring field in m_Fields)
            {
                if (field.Prefab != null && field.Prefab.name == fieldName)
                {
                    return field.Prefab;
                }
            }

            return null;
        }

        /// <summary>
        /// A gateway has to be reachable and must not be where a player arrives: a spawn point inside one sends the
        /// player straight back out the moment they land.
        /// </summary>
        private static void ValidateGateway(GameObject prefab, FieldEntity entity, string entityName, List<string> problems)
        {
            if (!entity.ScriptDefinition.TryGetScriptIndex(FieldScriptType.Gateway, out _))
            {
                return;
            }

            if (entity.ScriptDefinition.TryGetScriptIndex(FieldScriptType.OnEnter, out _))
            {
                problems.Add($"{entityName} has both a {nameof(FieldScriptType.Gateway)} and an {nameof(FieldScriptType.OnEnter)} script. Both run on entering, in the same slot, so only one would — put the other on its own entity");
            }

            FieldCollisionTrigger trigger = entity.GetComponentInChildren<FieldCollisionTrigger>(true);

            if (trigger == null)
            {
                problems.Add($"{entityName} has a {nameof(FieldScriptType.Gateway)} script but no {nameof(FieldCollisionTrigger)}, so nothing runs it");
                return;
            }

            if (!trigger.TryGetComponent(out BoxCollider box))
            {
                return;
            }

            if (!box.isTrigger)
            {
                problems.Add($"{entityName}'s gateway has a solid {nameof(BoxCollider)}, so it blocks the player instead of letting them through — tick Is Trigger");
            }

            foreach (SpawnPoint spawnPoint in prefab.GetComponentsInChildren<SpawnPoint>(true))
            {
                if (Contains(box, spawnPoint.Position))
                {
                    problems.Add($"{prefab.name} / spawn point '{spawnPoint.name}' is inside {entityName}'s gateway, so a player arriving there leaves again at once");
                }
            }
        }

        /// <summary>
        /// Worked out from the box's own space, because a prefab that is not in a scene has no physics bounds.
        /// </summary>
        private static bool Contains(BoxCollider box, Vector3 worldPoint)
        {
            Vector3 local  = box.transform.InverseTransformPoint(worldPoint) - box.center;
            Vector3 extent = box.size * 0.5f;

            bool inside = Mathf.Abs(local.x) <= extent.x && Mathf.Abs(local.y) <= extent.y && Mathf.Abs(local.z) <= extent.z;

            return inside;
        }

        public void BuildAssetBundles()
        {
            int count = m_Fields.Count;
            if (count == 0)
            {
                return;
            }

            List<string> problems = ValidateFields();

            if (problems.Count > 0)
            {
                Debug.LogError($"{nameof(FieldDatabase)}::{nameof(BuildAssetBundles)} Not building — {problems.Count} problem(s) in the fields:\n  {string.Join("\n  ", problems)}");
                return;
            }

            if (Directory.Exists(m_AssetBundlesPath))
            {
                Directory.Delete(m_AssetBundlesPath, true);
            }

            Directory.CreateDirectory(m_AssetBundlesPath);

            AssetBundleBuild[] fieldsToBuild = new AssetBundleBuild[count];

            for (int i = 0; i < count; i++)
            {
                string prefabPath = AssetDatabase.GetAssetPath(m_Fields[i].Prefab);

                fieldsToBuild[i] = new AssetBundleBuild
                                   {
                                       assetBundleName = m_Fields[i].Prefab.name,
                                       assetNames      = new string[] { prefabPath }
                                   };
            }

            const BuildAssetBundleOptions options = BuildAssetBundleOptions.ChunkBasedCompression | BuildAssetBundleOptions.StrictMode;

            BuildPipeline.BuildAssetBundles(m_AssetBundlesPath, fieldsToBuild, options, EditorUserBuildSettings.activeBuildTarget);

            AssetDatabase.Refresh();
        }
    }
}