using System;
using System.IO;
using System.Text;
using RPGFramework.Localisation.Editor;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace RPGFramework.Field.Editor
{

    [Serializable]
    public class FieldDatabaseAssetAuthoring
    {
        public GameObject               Prefab;
        public LocalisationSheetAsset[] LocalisationSheets;
    }

    [CreateAssetMenu(fileName = "Field Database", menuName = "RPG Framework/Field/Field Database")]
    public class FieldDatabaseScriptableObject : ScriptableObject
    {
        private readonly string m_AssetBundlesPath = Path.Combine(Application.streamingAssetsPath, "Field");

        public FieldDatabaseAssetAuthoring[] m_Fields;

        public void BuildScriptFile(string path, string filename, string namespaceForScript)
        {
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            string filePath = Path.Combine(path, filename);

            if (File.Exists(filePath))
            {
                File.Delete(filePath);
            }

            StringBuilder sb             = new StringBuilder();
            string        scriptFileName = filename.Split('.')[0];

            sb.AppendLine("// THIS FILE IS AUTOGENERATED, DO NOT MODIFY");
            sb.AppendLine($"// Last generated at {DateTime.UtcNow}\n");

            sb.AppendLine("using RPGFramework.Field;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceForScript}");
            sb.AppendLine("{");

            sb.AppendLine($"\tinternal class {scriptFileName.Replace(" ", "")} : IFieldDatabase");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tprivate readonly FieldDatabaseAsset[] m_Fields;");
            sb.AppendLine();
            sb.AppendLine($"\t\tinternal {scriptFileName.Replace(" ", "")}()");
            sb.AppendLine("\t\t{");

            sb.AppendLine("\t\t\tstring assetBundlesPath = Path.Combine(Application.streamingAssetsPath, \"Field\");");
            sb.AppendLine("\t\t\tm_Fields = new FieldDatabaseAsset[]");
            sb.AppendLine("\t\t\t{");
            for (int i = 0; i < m_Fields.Length; i++)
            {
                sb.AppendLine($"\t\t\t\tnew FieldDatabaseAsset(\"{m_Fields[i].Prefab.name}\", Path.Combine(assetBundlesPath, \"{m_Fields[i].Prefab.name.ToLower()}\"),");
                sb.AppendLine("\t\t\t\t\tnew string[]");
                sb.AppendLine("\t\t\t\t\t{");
                for (int j = 0; j < m_Fields[i].LocalisationSheets.Length; j++)
                {
                    sb.AppendLine($"\t\t\t\t\t\t\"{m_Fields[i].LocalisationSheets[j].SheetName}\",");
                }
                sb.AppendLine("\t\t\t\t\t}");
                sb.AppendLine($"\t\t\t\t),");
            }
            sb.AppendLine("\t\t\t};");

            sb.AppendLine("\t\t}");

            sb.AppendLine();

            sb.AppendLine("\t\tFieldDatabaseAsset IFieldDatabase.Get(int index)");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\treturn m_Fields[index];");
            sb.AppendLine("\t\t}");

            sb.AppendLine("\t}");

            sb.AppendLine("}");

            string file = sb.ToString();

            File.WriteAllText(filePath, file);

            AssetDatabase.Refresh();
        }

        public void BuildAssetBundles()
        {
            if (m_Fields.Length == 0)
            {
                return;
            }

            if (Directory.Exists(m_AssetBundlesPath))
            {
                Directory.Delete(m_AssetBundlesPath, true);
            }

            Directory.CreateDirectory(m_AssetBundlesPath);

            AssetBundleBuild[] fieldsToBuild = new AssetBundleBuild[m_Fields.Length];

            for (int i = 0; i < m_Fields.Length; i++)
            {
                string prefabPath = AssetDatabase.GetAssetPath(m_Fields[i].Prefab);

                fieldsToBuild[i] = new AssetBundleBuild
                                   {
                                           assetBundleName = m_Fields[i].Prefab.name,
                                           assetNames      = new string[] { prefabPath }
                                   };
            }

            BuildPipeline.BuildAssetBundles(m_AssetBundlesPath, fieldsToBuild, BuildAssetBundleOptions.StrictMode, EditorUserBuildSettings.activeBuildTarget);

            AssetDatabase.Refresh();
        }
    }

    [CustomEditor(typeof(FieldDatabaseScriptableObject))]
    public class FieldDatabaseScriptableObjectEditor : UnityEditor.Editor
    {
        private ModalWindow m_Window;

        public override VisualElement CreateInspectorGUI()
        {
            VisualElement root = new VisualElement();

            InspectorElement.FillDefaultInspector(root, serializedObject, this);

            Button generateFieldDatabaseScriptButton = new Button(OnGenerateFieldDatabaseScriptButtonClicked)
                                                       {
                                                               text = "Generate FieldDatabase script"
                                                       };

            root.Add(generateFieldDatabaseScriptButton);

            Button generateAssetBundlesButton = new Button(OnGenerateAssetBundlesButtonClicked)
                                                {
                                                        text = "Generate Asset Bundles"
                                                };

            root.Add(generateAssetBundlesButton);

            return root;
        }

        private void OnGenerateFieldDatabaseScriptButtonClicked()
        {
            m_Window           =  CreateInstance<ModalWindow>();
            m_Window.OnConfirm += OnGenerateFieldDatabaseScriptButtonClickedCallback;

            m_Window.Init(nameof(FieldDatabaseScriptableObject), "Generate Asset Bundles and FieldDatabase script", "FieldDatabase.cs");
        }

        private void OnGenerateFieldDatabaseScriptButtonClickedCallback(string path, string filename, string namespaceForScript)
        {
            m_Window.OnConfirm -= OnGenerateFieldDatabaseScriptButtonClickedCallback;
            m_Window           =  null;

            FieldDatabaseScriptableObject fieldDatabase = (FieldDatabaseScriptableObject)serializedObject.targetObject;

            fieldDatabase.BuildScriptFile(path, filename, namespaceForScript);
        }

        private void OnGenerateAssetBundlesButtonClicked()
        {
            FieldDatabaseScriptableObject fieldDatabase = (FieldDatabaseScriptableObject)serializedObject.targetObject;

            fieldDatabase.BuildAssetBundles();
        }
    }

    public class ModalWindow : EditorWindow
    {
        public event Action<string, string, string> OnConfirm;

        private TextField m_PathTextField;
        private TextField m_FileNameTextField;
        private TextField m_NamespaceTextField;

        private string m_SelectedDirectory;
        private string m_AssetType;
        private string m_FileName;

        public void Init(string assetType, string windowTitle, string filename)
        {
            m_AssetType         = assetType;
            m_FileName          = filename;
            titleContent        = new GUIContent(windowTitle);
            minSize             = new Vector2(600, 200);
            m_SelectedDirectory = EditorPrefs.GetString($"{Application.productName}_SelectedDirectory_{m_AssetType}", Application.dataPath);
            ShowModal();
        }

        public void CreateGUI()
        {
            VisualElement root = rootVisualElement;

            root.style.paddingTop    = 10;
            root.style.paddingBottom = 10;
            root.style.paddingLeft   = 10;
            root.style.paddingRight  = 10;
            root.style.flexDirection = FlexDirection.Column;

            VisualElement pathRow = new VisualElement
                                    {
                                            style =
                                            {
                                                    flexDirection = FlexDirection.Row,
                                                    alignItems    = Align.FlexEnd
                                            }
                                    };

            m_PathTextField = new TextField("Path:")
                              {
                                      value = m_SelectedDirectory
                              };
            m_PathTextField.style.flexGrow = 1;

            Button browseButton = new Button(OnBrowseClicked)
                                  {
                                          text = "Browse"
                                  };
            browseButton.style.flexShrink = 0;

            pathRow.Add(m_PathTextField);
            pathRow.Add(browseButton);

            if (m_FileName != null)
            {
                m_FileNameTextField = new TextField("File Name:")
                                      {
                                              value = EditorPrefs.GetString($"{Application.productName}_FileName_{m_AssetType}", m_FileName)
                                      };
            }

            m_NamespaceTextField = new TextField("Namespace:")
                                   {
                                           value = EditorPrefs.GetString($"{Application.productName}_Namespace_{m_AssetType}", "MyNamespace")
                                   };

            VisualElement buttonRow = new VisualElement
                                      {
                                              style =
                                              {
                                                      flexDirection  = FlexDirection.Row,
                                                      justifyContent = Justify.SpaceBetween
                                              }
                                      };

            Button continueButton = new Button(OnButtonConfirm)
                                    {
                                            text = "Generate"
                                    };

            buttonRow.Add(continueButton);

            root.Add(pathRow);
            if (m_FileName != null)
            {
                root.Add(m_FileNameTextField);
            }
            root.Add(m_NamespaceTextField);
            root.Add(buttonRow);
        }

        private void OnBrowseClicked()
        {
            string folderPath = EditorUtility.OpenFolderPanel("Select Folder", m_SelectedDirectory, string.Empty);

            if (!string.IsNullOrEmpty(folderPath))
            {
                m_SelectedDirectory   = folderPath;
                m_PathTextField.value = m_SelectedDirectory;
            }
        }

        private void OnButtonConfirm()
        {
            EditorPrefs.SetString($"{Application.productName}_SelectedDirectory_{m_AssetType}", m_SelectedDirectory);
            if (m_FileName != null)
            {
                EditorPrefs.SetString($"{Application.productName}_FileName_{m_AssetType}", m_FileNameTextField.value);
            }
            EditorPrefs.SetString($"{Application.productName}_Namespace_{m_AssetType}", m_NamespaceTextField.value);

            OnConfirm?.Invoke(m_SelectedDirectory, m_FileNameTextField?.value, m_NamespaceTextField.value);
            Close();
        }
    }
}